### PR TITLE
Review: README.md

### PR DESCRIPTION
**Pull request by frankebersoll**
#### Fixes
- Changed `require('exceptionless.node')` to `require('exceptionless')`.
#### Enhancements
- Streamlined badges format, added npm badge.
- Added "Show me the code!" quick start section.
- Fixed markdown intendation.
- Replaced "JavaScript" with "Browser" (Node.js is also JavaScript).
- Refactored last section into "Support" and "Contributing".
- Some small edits.

### CODE REVIEW

**Comment by ejsmith** [comment]
This looks good to me! @niemyjski?

**Comment by niemyjski** [comment]
I had used exceptionless.node because using require('exceptionless') was loading the browser version which uses a umd format. And thus you don't get any of the node code to load. If you can verify that this does in deed work now lets make this change.

**Comment by frankebersoll** [comment]
The documentation assumes that you have downloaded and installed Exceptionless using npm. When you do this, it will install Exceptionless in the `node_modules/exceptionless` folder, as the node package is named `exceptionless`. That's how `require` will find it. The browser version will only be loaded during Excepionless client development, when your root happens to be our git root. Then, you should use `require("./dist/exceptionless.node")`, but developers will figure this out i hope.

**Comment by niemyjski** [comment]
Might want to put that under the developer wiki or read. I guess it goes off of the packages.config for the main script?

**Comment by frankebersoll** [comment]
Just doing this. Yes, it does! Nice writeup how it works: https://nodejs.org/api/modules.html#modules_all_together

I also changed `--save-dev` to `--save`, because Exceptionless is not a development dependency but will usually need to ship with the software.

**Comment by niemyjski** [comment]
:+1:

**Pull request merged**
