### PR TITLE
Feature: Populate module info with installed node modules

### PR DESCRIPTION
**Pull request by frankebersoll**
This feature (Issue #6) adds a `NodeModuleCollector.ts` that tries to find all currently loaded npm modules:
1. It synchronously runs `npm ls --depth=0 --json` to get all installed packages on root level. Those modules are cached, as they won't change during runtime.
2. It checks `require.cache` to get all currently cached modules. Those are all JavaScript files that have been required since startup of the application.
3. It crops all those paths to get the portion behind `/node_modules/`, which is the module name, and makes them unique.
4. It returns all installed packages from 1. that match those module names.

### CODE REVIEW

**Comment by niemyjski** [comment]
Awesome job

**Comment by niemyjski** [comment]
Is this ready to be tested and merged?

**Comment by frankebersoll** [comment]
Absolutley. Currently working on https://github.com/exceptionless/Exceptionless.JavaScript/issues/8 for it to make it into the same release.

**Comment by ejsmith** [comment]
Awesome!

**Comment by frankebersoll** [comment]
This now contains support for additional properties (https://github.com/exceptionless/Exceptionless.JavaScript/issues/8), including some unit tests to check for compatibility with common browser properties.

**Comment by niemyjski** [comment]
Awesome!

**Pull request merged**
